export const POST_ORDERS_REQUEST = "POST_ORDERS_REQUEST"
export const POST_ORDERS_SUCCESS = "POST_ORDERS_SUCCESS"
export const POST_ORDERS_FAIL = "POST_ORDERS_FAIL"

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST"
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL"
