export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAIL = "POST_ORDER_FAIL";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const PUT_ORDER_REQUEST = "PUT_ORDER_REQUEST";
export const PUT_ORDER_SUCCESS = "PUT_ORDER_SUCCESS";
export const PUT_ORDER_FAIL = "PUT_ORDER_FAIL";

export const RESET_ORDER = "RESET_ORDER";

export const GET_ALLORDERS_REQUEST = "GET_ALLORDERS_REQUEST";
export const GET_ALLORDERS_SUCCESS = "GET_ALLORDERS_SUCCESS";
export const GET_ALLORDERS_FAIL = "GET_ALLORDERS_FAIL";
export const RESET_ALLORDERS = "RESET_ALLORDERS";

export const ADMIN_GET_ALLORDERS_REQUEST = "ADMIN_GET_ALLORDERS_REQUEST";
export const ADMIN_GET_ALLORDERS_SUCCESS = "ADMIN_GET_ALLORDERS_SUCCESS";
export const ADMIN_GET_ALLORDERS_FAIL = "ADMIN_GET_ALLORDERS_FAIL";

export const PUT_ORDER_DELIVER_REQUEST = "PUT_ORDER_DELIVER_REQUEST";
export const PUT_ORDER_DELIVER_SUCCESS = "PUT_ORDER_DELIVER_SUCCESS";
export const PUT_ORDER_DELIVER_FAIL = "PUT_ORDER_DELIVER_FAIL";
